### ISSUE TITLE
Go command in Makefile moved

### ISSUE THREAD

**Issue by elowing** [justincampbell/tmux-pomodoro#3]
==> make install PREFIX=/usr/local/Cellar/tmux-pomodoro/1.1.1

go get -t
go get code.google.com/p/go.tools/cmd/cover
the code.google.com/p/go.tools/cmd/cover command has moved; use golang.org/x/tools/cmd/cover instead.

**Comment by justincampbell** [comment]
Thanks! https://github.com/justincampbell/tmux-pomodoro/commit/202c7d88da7723a32761e9cfc5f5116769a3b2f4
